"""empty message

Revision ID: 1cd11a0be4f8
Revises: ed81f275020e
Create Date: 2022-10-14 18:05:51.491252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd11a0be4f8'
down_revision = 'ed81f275020e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('heatLoad', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'heatLoad')
    # ### end Alembic commands ###
