"""empty message

Revision ID: ce3017e2eb86
Revises: f5a36f80d21b
Create Date: 2022-09-01 13:04:43.665311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce3017e2eb86'
down_revision = 'f5a36f80d21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therb', sa.Column('sensibleLoad', sa.JSON(), nullable=True))
    op.add_column('therb', sa.Column('latentLoad', sa.JSON(), nullable=True))
    op.drop_column('therb', 'latentHeat')
    op.drop_column('therb', 'sensibleHeat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therb', sa.Column('sensibleHeat', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('therb', sa.Column('latentHeat', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('therb', 'latentLoad')
    op.drop_column('therb', 'sensibleLoad')
    # ### end Alembic commands ###
